# Generated by Django 6.0.2 on 2026-04-02 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_conversation'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='room_name',
            field=models.CharField(default='sdff', unique=True),
            preserve_default=False,
        ),
    ]
